name       : zsync
version    : 0.6.2
release    : 2
homepage   : http://zsync.moria.org.uk/
source     :
    - http://zsync.moria.org.uk/download/zsync-0.6.2.tar.bz2 : 0b9d53433387aa4f04634a6c63a5efa8203070f2298af72a705f9be3dda65af2
license    : Artistic-2.0
summary    : zsync is a file transfer program.
builddeps  :
description: |
    zsync is a file transfer program. It allows you to download a file from a remote server, where you have a copy of an older version of the file on your computer already. zsync downloads only the new parts of the file.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
